### ISSUE TITLE
Provide a use demo

### ISSUE THREAD

**Issue by lizubing1992** [dimitrovskif/SmartCache#1]

**Comment by dimitrovskif** [comment]
Older commit contains a demo app: https://github.com/dimitrovskif/SmartCache/tree/58d4152a46e668f159c9e6ff0071278f657758e1/demo_app

However, it was deleted because it is very basic and not much useful. If you need help building a demo, tell me and I can help you. (Will happily merge a PR if you commit it too)

**Comment by lizubing1992** [comment]
thanks
